// Generated by CoffeeScript 1.4.0
(function() {
  var BodyForLifeTimerViewModel,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  BodyForLifeTimerViewModel = (function() {

    function BodyForLifeTimerViewModel() {
      this._tick = __bind(this._tick, this);
      this.timerGoing = ko.observable(false);
      this.startStopText = ko.computed(this._startStopText, this);
      this.timerCount = ko.observable(1200);
      this.timerText = ko.computed(this._timerText, this);
      this.intensityText = ko.computed(this._intensityText, this);
      this._secondIntervalHandle = setInterval(this._tick, 1000);
    }

    BodyForLifeTimerViewModel.prototype._startStopText = function() {
      if (this.timerGoing()) {
        return 'Stop';
      } else {
        return 'Start';
      }
    };

    BodyForLifeTimerViewModel.prototype.toggleTimer = function(vm, event) {
      var going;
      going = this.timerGoing();
      return this.timerGoing(!going);
    };

    BodyForLifeTimerViewModel.prototype._timerText = function() {
      var minutes, seconds;
      seconds = this.timerCount();
      minutes = Math.floor(seconds / 60);
      seconds = seconds % 60;
      if (seconds < 10) {
        seconds = "0" + seconds;
      }
      return "" + minutes + ":" + seconds;
    };

    BodyForLifeTimerViewModel.prototype.timeToIntensity = function() {};

    BodyForLifeTimerViewModel.prototype._intensityText = function() {
      var intensity, interval, intervalIntensities;
      intervalIntensities = [5, 10, 9, 8, 7, 9, 8, 7, 9, 8, 7, 9, 8, 7, 9, 8, 7, 6, 5, 5];
      interval = Math.floor(this.timerCount() / 60);
      intensity = intervalIntensities[interval];
      return intensity;
    };

    BodyForLifeTimerViewModel.prototype._tick = function() {
      if (this.timerGoing()) {
        this.timerCount(this.timerCount() - 1);
        if (this.timerCount() % 60 === 0) {
          return this._playIntervalChangeSound();
        }
      }
    };

    BodyForLifeTimerViewModel.prototype.addTime = function() {
      return this.timerCount(this.timerCount() + 10);
    };

    BodyForLifeTimerViewModel.prototype.subtractTime = function() {
      return this.timerCount(this.timerCount() - 10);
    };

    BodyForLifeTimerViewModel.prototype._playIntervalChangeSound = function() {};

    return BodyForLifeTimerViewModel;

  })();

  $(document).ready(function() {
    var timerVM;
    timerVM = new BodyForLifeTimerViewModel();
    return ko.applyBindings(timerVM);
  });

}).call(this);
